# ------- Branding Related Config ------- #
- name: INSTALLATION_NAME
  value: 'Dooza Desk'
- name: LOGO_THUMBNAIL
  value: '/brand-assets/logo_thumbnail.svg'
- name: LOGO
  value: '/brand-assets/logo.svg'
- name: LOGO_DARK
  value: '/brand-assets/logo_dark.svg'
- name: BRAND_URL
  value: 'https://www.doozadesk.com'
- name: WIDGET_BRAND_URL
  value: 'https://www.doozadesk.com'
- name: BRAND_NAME
  value: 'Dooza Desk'
- name: TERMS_URL
  value: 'https://www.doozadesk.com/terms-of-service'
- name: PRIVACY_URL
  value: 'https://www.doozadesk.com/privacy-policy'
- name: DISPLAY_MANIFEST
  value: true
# ------- End of Branding Related Config ------- #

# ------- Signup & Account Related Config ------- #
- name: ENABLE_ACCOUNT_SIGNUP
  value: true
# ------- End of Account Related Config ------- #
