slack:
  id: slack
  logo: slack.png
  i18n_key: slack
  action: https://slack.com/oauth/v2/authorize?scope=commands,chat:write,channels:read,channels:manage,channels:join,groups:write,im:write,mpim:write,users:read,users:read.email,chat:write.customize,channels:history,groups:history,mpim:history,im:history
webhooks:
  id: webhook
  logo: cable.svg
  i18n_key: webhooks
  action: /webhook
dialogflow:
  id: dialogflow
  logo: dialogflow.svg
  i18n_key: dialogflow
  action: /dialogflow
