services:
  base: &base
    image: joaonasser/chatfy:homolog
    env_file: .env
    command: irb
    tty: true
    stdin_open: true
    volumes:
      - /data/storage:/app/storage

  rails:
    <<: *base
    ports:
      - '80:3000'
    environment:
      - EXECJS_RUNTIME:Disabled
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
    entrypoint: docker/entrypoints/rails.sh
    command: [ 'bundle', 'exec', 'rails', 's', '-p', '3000', '-b', '0.0.0.0' ]
    restart: always

  sidekiq:
    <<: *base
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
    command: [ 'bundle', 'exec', 'sidekiq', '-C', 'config/sidekiq.yml' ]
    restart: always
