#pusher

pusher_app_id: ''
pusher_key: ''
pusher_secret: ''
pusher_cluster: ''

#fb app
fb_verify_token: ''
fb_app_secret: ''
fb_app_id: ''

#ses

ses_address:
ses_username:
ses_password:

#misc
frontend_url: ''

#s3

S3_BUCKET_NAME: ''
AWS_ACCESS_KEY_ID:
AWS_SECRET_ACCESS_KEY:
AWS_REGION: ''


#chargebee
CHARGEBEE_API_KEY: ''
CHARGEBEE_SITE: ''
CHARGEBEE_WEBHOOK_USERNAME: ''
CHARGEBEE_WEBHOOK_PASSWORD: ''

#sentry
SENTRY_DSN: ''
