# DO NOT change the order of features EVER
- name: inbound_emails
  enabled: true
- name: channel_email
  enabled: true
- name: channel_facebook
  enabled: true
- name: channel_twitter
  enabled: true
- name: ip_lookup
  enabled: false
- name: disable_branding
  enabled: false
- name: email_continuity_on_api_channel
  enabled: false
