# if you dont specify locked attribute, the default value will be true
# which means the particular config will be locked
- name: INSTALLATION_NAME
  value: 'Atoomo'
- name: LOGO_THUMBNAIL
  value: '/brand-assets/atoomo.svg'
- name: LOGO
  value: '/brand-assets/atoomo_logo.svg'
- name: BRAND_URL
  value: 'https://atoomo.io'
- name: WIDGET_BRAND_URL
  value: 'https://atoomo.io'
- name: BRAND_NAME
  value: 'Atoomo'
- name: TERMS_URL
  value: 'https://atoomo.io/terms-of-service'
- name: PRIVACY_URL
  value: 'https://atoomo.io/privacy-policy'
- name: DISPLAY_MANIFEST
  value: true
- name: MAILER_INBOUND_EMAIL_DOMAIN
  value:
  locked: false
- name: MAILER_SUPPORT_EMAIL
  value:
  locked: false
- name: CREATE_NEW_ACCOUNT_FROM_DASHBOARD
  value: false
  locked: false
- name: INSTALLATION_EVENTS_WEBHOOK_URL
  value:
  locked: false
- name: CHATWOOT_INBOX_TOKEN
  value:
  locked: false
- name: CHATWOOT_INBOX_HMAC_KEY
  value:
  locked: false
- name: API_CHANNEL_NAME
  value:
- name: API_CHANNEL_THUMBNAIL
  value:
- name: ANALYTICS_TOKEN
  value:
- name: ANALYTICS_HOST
  value:
- name: DIRECT_UPLOADS_ENABLED
  value: false
  locked: false
- name: HCAPTCHA_SITE_KEY
  value:
  locked: false
- name: HCAPTCHA_SERVER_KEY
  value:
  locked: false
- name: LOGOUT_REDIRECT_LINK
  value: /app/login
  locked: false
- name: DISABLE_USER_PROFILE_UPDATE
  value: false
  locked: false
- name: ENABLE_MESSENGER_CHANNEL_HUMAN_AGENT
  value: false
  locked: false
- name: CSML_BOT_HOST
  value:
  locked: false
- name: CSML_BOT_API_KEY
  value:
  locked: false
- name: CHATWOOT_CLOUD_PLANS
  value:
- name: DEPLOYMENT_ENV
  value: self-hosted
