# if you dont specify locked attribute, the default value will be true
# which means the particular config will be locked
- name: INSTALLATION_NAME
  value: 'MaaS.work Chat'
- name: LOGO_THUMBNAIL
  value: '/brand-assets/logo_thumbnail.svg'
- name: LOGO
  value: '/brand-assets/logo.svg'
- name: BRAND_URL
  value: 'https://www.maas.work'
- name: WIDGET_BRAND_URL
  value: 'https://www.maas.work'
- name: BRAND_NAME
  value: 'MaaS.work Chat'
- name: TERMS_URL
  value: 'https://www.maas.work'
- name: PRIVACY_URL
  value: 'https://www.maas.work'
- name: DISPLAY_MANIFEST
  value: true
- name: MAILER_INBOUND_EMAIL_DOMAIN
  value:
  locked: false
- name: MAILER_SUPPORT_EMAIL
  value:
  locked: false
- name: CREATE_NEW_ACCOUNT_FROM_DASHBOARD
  value: false
  locked: false
- name: INSTALLATION_EVENTS_WEBHOOK_URL
  value:
  locked: false
- name: CHATWOOT_INBOX_TOKEN
  value:
  locked: false
- name: CHATWOOT_INBOX_HMAC_KEY
  value:
  locked: false
