providers:
  openai:
    display_name: 'OpenAI'
    logo: openai.png
  anthropic:
    display_name: 'Anthropic'
    logo: anthropic.png

models:
  gpt-4.1:
    provider: openai
    display_name: 'GPT-4.1'
    credit_multiplier: 0.5
  gpt-4.1-mini:
    provider: openai
    display_name: 'GPT-4.1 Mini'
    credit_multiplier: 0.3
  gpt-4.1-nano:
    provider: openai
    display_name: 'GPT-4.1 Nano'
    credit_multiplier: 0.1
  gpt-5:
    provider: openai
    display_name: 'GPT-5'
    credit_multiplier: 1
  gpt-5.1:
    provider: openai
    display_name: 'GPT-5.1'
    credit_multiplier: 1.2
  gpt-5-mini:
    provider: openai
    display_name: 'GPT-5 Mini'
    credit_multiplier: 0.8
  gpt-5-nano:
    provider: openai
    display_name: 'GPT-5 Nano'
    credit_multiplier: 0.3
  gpt-5.2:
    provider: openai
    display_name: 'GPT-5.2'
    credit_multiplier: 1.5
  claude-haiku-4.5:
    provider: anthropic
    display_name: 'Claude Haiku 4.5'
    coming_soon: true
    credit_multiplier: 1
  claude-sonnet-4:
    provider: anthropic
    display_name: 'Claude Sonnet 4'
    coming_soon: true
    credit_multiplier: 2
  whisper-1:
    provider: openai
    display_name: 'Whisper'
    credit_multiplier: 0.2
  text-embedding-3-small:
    provider: openai
    display_name: 'Text Embedding 3 Small'
    credit_multiplier: 0.1

features:
  editor:
    models:
      [
        gpt-4.1-mini,
        gpt-4.1-nano,
        gpt-5-mini,
        gpt-4.1,
        gpt-5,
        gpt-5.1,
        gpt-5.2,
        claude-haiku-4.5,
      ]
    default: gpt-4.1-mini
  assistant:
    models:
      [
        gpt-5-mini,
        gpt-4.1,
        gpt-5,
        gpt-5.1,
        gpt-5.2,
        claude-haiku-4.5,
        claude-sonnet-4,
      ]
    default: gpt-5.2
  copilot:
    models:
      [
        gpt-5-mini,
        gpt-4.1,
        gpt-5,
        gpt-5.1,
        gpt-5.2,
        claude-haiku-4.5,
        claude-sonnet-4,
      ]
    default: gpt-5.2
  label_suggestion:
    models: [gpt-4.1-nano, gpt-4.1-mini, gpt-5-mini]
    default: gpt-4.1-nano
  audio_transcription:
    models: [whisper-1]
    default: whisper-1
  help_center_search:
    models: [text-embedding-3-small]
    default: text-embedding-3-small
# add deprecation_map later
