active:
  v1:
    paid:
      name: 'Platinum'
      id: 'v1-platinum'
      price: 29
    trial:
      name: 'Trial'
      id: 'v1Trial'
      price: 0
inactive:
  v0:
    free:
      name: 'Free'
      price: 0
trial_period: 365
default_pricing_version: 'v1'
