defaults: &defaults
  host: 0.0.0.0
  port: 6379
  namespace: "local"

development:
  <<: *defaults

slave:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults
