name: Deploy Staging

on:
  push:
    branches: 
      - develop
  workflow_dispatch:
  
  

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and publish Docker image into AWS ECR for Birdwoot
        uses: ./.github/actions/deployment/push-image-ecr
        with:
          BRANCH: develop
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_STAGING }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_STAGING }}
          VUE_APP_SENTRY_DSN_CHAT: ${{ secrets.VUE_APP_SENTRY_DSN_CHAT }}
          VUE_APP_VERSION: $(git rev-parse --short HEAD)
          ECR_REGISTRY: 823532849758.dkr.ecr.us-east-1.amazonaws.com
          ECR_REPOSITORY: conversations/birdwoot/staging/birdwootmain
          DOCKERFILE_PATH: docker/Dockerfile
      
      - name: Build and publish Docker image into AWS ECR for Sidekiq
        uses: ./.github/actions/deployment/push-image-ecr
        with:
          BRANCH: develop
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_STAGING }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_STAGING }}
          ECR_REGISTRY: 823532849758.dkr.ecr.us-east-1.amazonaws.com
          ECR_REPOSITORY: conversations/birdwoot/staging/sidekiq
          DOCKERFILE_PATH: docker/dockerfiles/sidekiq.Dockerfile

      # Send status notification
      - name: Build Slack notification payload
        id: slack-payload
        if: ${{ always() }}
        env:
          BRANCH_NAME: ${{ github.ref_name }}
          JOB_STATUS: ${{ job.status }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_RUN_ID: ${{ github.run_id }}
        run: ./scripts/build_slack_deployment_status_notification_payload.sh

      - name: Notify status to slack
        if: ${{ always() }}
        uses: slackapi/slack-github-action@v1.14.0
        with:
          payload: ${{ steps.slack-payload.outputs.payload }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
